print("---Info---")
    # print("Sex: "+DBManager.getSex(database,username))
    # print("Age: "+ str(DBManager.getAge(database,username)))
    # print("Weight: " + str(DBManager.getWeight(database,username)) +"lbs")
    # print("Height: " + DBManager.getHeightStr(database,username))